
#include <stdio.h>
#include <stdlib.h>
#include "ArrayEmployees.h"
#include "RJimenez.h"


#define TAM_EMPLOYEE 1000
#define BIENVENIDA "BIENVENIDO AL ABM DE EMPLEADOS\n"
#define MENSAJE_OPCION_UNO "1.ALTAS\n"
#define MENSAJE_OPCION_DOS "2.MODIFICAR\n"
#define MENSAJE_OPCION_TRES "3.BAJA\n"
#define MENSAJE_OPCION_CUATRO "4.INFORMAR\n"
#define MENSAJE_OPCION_CINCO "5.SALIR\n"
#define MENSAJE_INGRESAR_OPCION "INGRESE UNA OPCION: "
#define MENSAJE_ERROR "INGRESO UNA OPCION INCORRECTA, VUELVA A INGRESAR UNA OPCION\n"
#define MENSAJE_PEDIR_NOMBRE "INGRESE EL NOMBRE DEL EMPLEADO: "
#define MENSAJE_PEDIR_APELLIDO "INGRESE EL APELLIDO DEL EMPLEADO: "
#define MENSAJE_DE_ERROR_NOMBRE "ERROR EN EL INGRESO DEL NOMBRE\n\n"
#define MENSAJE_DE_ERROR_APELLIDO "ERROR EN EL INGRESO DEL APELLIDO\n\n"
#define MENSAJE_PEDIR_SALARIO "INGRESE EL SALARIO DEL EMPLEADO: "
#define MENSAJE_DE_ERROR_SALARIO "ERROR EN EL INGRESO DEL SALARIO\n\n"
#define MENSAJE_PEDIR_SECTOR "INGRESE EL SECTOR DEL EMPLEADO: "
#define MENSAJE_ERROR_SECTOR "ERRPR EN EL INGRESO DEL SECTOR\n\n"
#define MENSAJE_DE_ERROR_LUGAR "NO HAY LUGAR PARA INGRESAR UN NUEVO EMPLEADO\n\n"
#define MENSAJE_EXITOSO_ALTA "EL ALTA DEL EMPLEADO FUE EXITOSA"
#define MENSAJE_ELIMINAR_EMPLEADO "POR FAVOR INGRESE EL ID DEL EMPLEADO QUE QUIERE ELIMINAR:"
#define MENSAJE_ERROR_ID "ERROR AL INGRESAR EL ID DEL EMPLEADO\n\n"
#define MENSAJE_ERROR_ID_NOENCONTRADO "EL ID INGRESADO NO FUE ENCONTRADO\n\n"
#define MENSAJE_EXITOSO_ELIMINAR "EL EMPLEADO FUE DADO DE BAJA CORRECTAMENTE\n\n"
#define MENSAJE_MODIFICAR "INGRESE EL ID DEL EMPLEADO QUE QUIERA MODIFICAR: "
#define MENSAJE_OPCIONES_MODIFICAR "ELIJA EL DATO A MODIFICAR:\n\t1. NOMBRE\n\t2. APELLIDO\n\t3. SUELDO\n\t4. SECTOR\n\nSU OPCION: "
#define MENSAJE_MODIFICAR_NOMBRE "INGRESE EL NUMERO NOMBRE: "
#define MENSAJE_MODIFICAR_APELLIDO "INGRESE EL NUMERO APELLIDO: "
#define MENSAJE_MODIFICAR_SUELDO "INGRESE EL NUMERO SUELDO: "
#define MENSAJE_MODIFICAR_SECTOR "INGRESE EL NUMERO SECTOR: "
#define MENSAJE_MODIFICAR_NOMBRE_EXITOSO "EL NOMBRE FUE MODIFICADO EXITOSAMENTE\n\n"
#define MENSAJE_MODIFICAR_NOMBRE_ERROR "ERROR AL INGRESAR EL NOMBRE\n\n"
#define MENSAJE_MODIFICAR_APELLIDO_EXITOSO "EL APELLIDO FUE MODIFICADO EXITOSAMENTE\n\n"
#define MENSAJE_MODIFICAR_APELLIDO_ERROR "ERROR AL INGRESAR EL APELLIDO\n\n"
#define MENSAJE_MODIFICAR_SUELDO_EXITOSO "EL SUELDO FUE MODIFICADO EXITOSAMENTE\n\n"
#define MENSAJE_MODIFICAR_SUELDO_ERROR "ERROR AL INGRESAR EL SUELDO\n\n"
#define MENSAJE_MODIFICAR_SECTOR_EXITOSO "EL SECTOR FUE MODIFICADO EXITOSAMENTE"
#define MENSAJE_MODIFICAR_SECTOR_ERROR "ERROR AL INGRESAR EL SECTOR\n\n"
#define MENSAJE_MODIFICAR_OPCION_ERROR "USTED INGRESO UNA OPCION DE MODIFICACION INVALIDA\n\n"
#define MENSAJE_OPCIONES_MOSTRAR "OPCIONES:\n\t1. MOTRAR ORDENADOS POR APELLIDO Y SECTOR\n\t2. PROMEDIO Y QUIENES SUPERAN EL PROMEDIO DE SUELDO\n\nSU OPCION: "
#define MENSAJE_MOSTRAR_ERROR "USTED NO HA INGRESADO UNA OPCION CORRECTA"
#define MENSAJE_OPCIONES_MOSTRAR_ORDENAR "INGRESE EL ORDENAMIENTO. NUMERO > 1 ASCENDENTE Y < 1 DESCENTE\n\nSU OPCION: "
#define MENSAJE_MOSTRAR_PROMEDIO "EL PROMEDIO DE SUELDO ES: "
#define MENSAJE_DE_DESPEDIDA "USTED HA SALIDO DEL SISTEMA\n"
#define MENSAJE_ERROR_SIN_EMPLEADOS "POR FAVOR, PARA HACER ESTA OPERACION, PRIMERO HAGA EL ALTA DE UN EMPLEADO\n"


int main(void) {

	setbuf(stdout, NULL);
	int opcion;
	int idEmpleado;
	int bandera = 1;
	Employee arrayPrincipal [1000];

	idEmpleado = 1;

	do
	{
		printf(BIENVENIDA);
		printf(MENSAJE_OPCION_UNO);
		printf(MENSAJE_OPCION_DOS);
		printf(MENSAJE_OPCION_TRES);
		printf(MENSAJE_OPCION_CUATRO);
		printf(MENSAJE_OPCION_CINCO);
		printf(MENSAJE_INGRESAR_OPCION);
		scanf("%d", &opcion);

		switch(opcion)
		{
			case '1':
				bandera = PedirEmpleado(MENSAJE_PEDIR_NOMBRE, MENSAJE_PEDIR_APELLIDO, MENSAJE_DE_ERROR_NOMBRE, MENSAJE_DE_ERROR_APELLIDO,
						MENSAJE_PEDIR_SALARIO, MENSAJE_DE_ERROR_SALARIO, MENSAJE_PEDIR_SECTOR, MENSAJE_ERROR_SECTOR, idEmpleado, arrayPrincipal,
						TAM_EMPLOYEE, MENSAJE_DE_ERROR_LUGAR, MENSAJE_EXITOSO_ALTA);
				idEmpleado++;
				break;
			case '2':
				if (bandera == 0)
				{
					ModificarEmpleado (MENSAJE_MODIFICAR, MENSAJE_ERROR_ID, MENSAJE_ERROR_ID_NOENCONTRADO, MENSAJE_OPCIONES_MODIFICAR,
							MENSAJE_MODIFICAR_NOMBRE, MENSAJE_MODIFICAR_APELLIDO, MENSAJE_MODIFICAR_NOMBRE_EXITOSO,
							MENSAJE_MODIFICAR_NOMBRE_ERROR, MENSAJE_MODIFICAR_APELLIDO_EXITOSO, MENSAJE_MODIFICAR_APELLIDO_ERROR,
							MENSAJE_MODIFICAR_SUELDO, MENSAJE_MODIFICAR_SUELDO_EXITOSO, MENSAJE_MODIFICAR_SUELDO_ERROR,
							MENSAJE_MODIFICAR_SECTOR, MENSAJE_MODIFICAR_SECTOR_EXITOSO, MENSAJE_MODIFICAR_SECTOR_ERROR,
							MENSAJE_MODIFICAR_OPCION_ERROR, arrayPrincipal, TAM_EMPLOYEE);
				}else
				{
					printf(MENSAJE_ERROR_SIN_EMPLEADOS);
				}
				break;
			case '3':
				if (bandera == 0)
				{
					EliminarEmpleado (MENSAJE_ELIMINAR_EMPLEADO, MENSAJE_ERROR_ID, MENSAJE_EXITOSO_ELIMINAR,
							MENSAJE_ERROR_ID_NOENCONTRADO, arrayPrincipal, TAM_EMPLOYEE);
					bandera = BuscarEmpleados (arrayPrincipal, TAM_EMPLOYEE);
				}else
				{
					printf (MENSAJE_ERROR_SIN_EMPLEADOS);
				}

				break;
			case '4':
				MostrarEmpleados (MENSAJE_OPCIONES_MOSTRAR, MENSAJE_MOSTRAR_ERROR, MENSAJE_OPCIONES_MOSTRAR_ORDENAR,
						MENSAJE_MOSTRAR_PROMEDIO, arrayPrincipal, TAM_EMPLOYEE);
				break;
			case '5':
				printf(MENSAJE_DE_DESPEDIDA);
				break;
			default:
				printf(MENSAJE_ERROR);
			break;
		}

	}while(opcion != 5);



	return EXIT_SUCCESS;
}
